server:
  port: 8080
  
awsregion: us-east-1

demo: ${demo}
#demo: hola

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false
    username: ${username}
    password: ${password}
    #url: jdbc:mysql://localhost:3306/encuestabd?zeroDateTimeBehavior=convertToNull
    #url: jdbc:mysql://localhost:3306/encuestabd?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false
    #username: root
    #password: 123456
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#AWS_COGNITO_REGION: us-east-1
#userPoolId: us-east-1_d1K3MSRQA
#clientId: 4u05df2qs4tj6urog4utebhmja
#AWS_ACCESS_KEY_ID: AKIAWFVD32KHTUIYD6ET
#AWS_SECRET_ACCESS_KEY: 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